backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\helpers\ArrayHelper;

use common\models\{
	Purpose,
	Project,
	UserProject,
	User,
	Login,
	SignUpForm
};

class SiteController extends Controller
{

	public function behaviors() {
		return [
			'access' => ['class' => AccessControl::className(),
			'rules' => [
				[
					'actions' => [
						'signup',
						'login',
						'error'
					],
					'allow' => true,
				],
				[
					'actions' => [
						'logout',
						'index',
						'w_index',
						'my',
						'add-project',
						'update-project',
						'join-to-project',
						'delete-project',
						'project',
						'down',
						'create',
						'update',
						'delete',
					],
					'allow' => true,
					'roles' => ['@'],
				],
			],
		],
	];
}

	public function actions() {
		return [
			'error' => [
				'class' => 'yii\web\ErrorAction',
			],
		];
	}

	public function actionIndex() {
		if (Yii::$app->user->isGuest) return $this->goHome();

		$model = Project::find()->orderBy(['date' => SORT_ASC]);
		if (User::isWorker()) {
			return $this->render('w_index', ['model' => $model]);
		} else {
			return $this->render('index', ['model' => $model]);
		}
	}

	public function actionMy() {
		if (Yii::$app->user->isGuest) return $this->goHome();

		$up = UserProject::find()->where(['user_id' => \Yii::$app->user->identity->id])->all();

		$ids = []; array_map(function($item)use(&$ids){ $ids[] = $item->project_id; }, $up);

		$model = Project::find()->where(['in', 'id', $ids])->orderBy(['date' => SORT_ASC]);
		return $this->render('my', ['model' => $model]);
	}

	public function actionProject($id) {
		if (Yii::$app->user->isGuest) return $this->goHome();
		$project = Project::find()->where(['id' => $id])->one();
		$model = Purpose::find()->where(['project_id' => $id]);
		$done = Purpose::find()->where(['project_id' => $id, 'status' => 1])->count();
		$all = $model->count();

		$up = UserProject::find()->where(['project_id' => $project->id])->all();
		$ids = []; array_map(function($item)use(&$ids){ $ids[] = $item->user_id; }, $up);
		$model2 = User::find()->where(['in', 'id', $ids]);

		if (User::isWorker()) {
			return $this->render('w_project', [
				'project' => $project,
				'model' => $model,
				'model2' => $model2,
				'done' => $done,
				'all' => $all,
			]);
		} else {
			return $this->render('project', [
				'project' => $project,
				'model' => $model,
				'model2' => $model2,
				'done' => $done,
				'all' => $all,
			]);
		}
	}

	public function actionCreate($id) {

		if (Yii::$app->user->isGuest) {
			return $this->goHome();
		}

		$model = new Purpose();

		if (Yii::$app->request->isPost) {
			$model->name = Yii::$app->request->post()['Purpose']['name'];
			$model->desc = Yii::$app->request->post()['Purpose']['desc'];
			$model->status = Yii::$app->request->post()['Purpose']['status'];
			$model->project_id = $id;
			$model->date = date('Y-m-d');
			$model->save();
			return $this->redirect(['/site/project', 'id' => $id]);
		}

		return $this->render('create', [
			'model' => $model,
			'statuses' => Purpose::allStatuses(),
			'projects' => $this->getProjects(),
		]);
	}

	public function actionUpdate($id) {
		if (Yii::$app->user->isGuest) {
			return $this->goHome();
		}

		$model = Purpose::findIdentity($id);

		if (Yii::$app->request->isPost) {
			$model->name = Yii::$app->request->post()['Purpose']['name'];
			$model->desc = Yii::$app->request->post()['Purpose']['desc'];
			$model->status = Yii::$app->request->post()['Purpose']['status'];
			$model->save();
			return $this->redirect(['/site/project', 'id' => $model->project_id]);
		}

		return $this->render('update', [
			'model' => $model,
			'statuses' => Purpose::allStatuses(),
			'projects' => $this->getProjects(),
		]);
	}

	public function actionDelete($id) {
		if (Yii::$app->user->isGuest) {
			return $this->goHome();
		}

		$model = Purpose::findIdentity($id);
		$model->delete();
		return $this->redirect(['index']);
	}

	public function actionAddProject() {
		if (Yii::$app->user->isGuest) {
			return $this->goHome();
		}

		$model = new Project();

		if ($model->load(Yii::$app->request->post()) && $model->validate()) {
			$model->title = Yii::$app->request->post()['Project']['title'];
			$model->desc = Yii::$app->request->post()['Project']['desc'];
			$model->save();
			return $this->redirect(['index']);
		}

		return $this->render('add-project', [
			'model' => $model,
		]);
	}

	public function actionJoinToProject($id) {
		if (Yii::$app->user->isGuest) return $this->goHome();

		$propj = Project::findOne($id);

		if ($propj != null) {
			$model = new UserProject();
			$model->user_id = \Yii::$app->user->identity->id;
			$model->project_id = $propj->id;
			$model->save();
		}

		return $this->redirect(['index']);
	}

	public function actionUpdateProject($id) {
		if (Yii::$app->user->isGuest) return $this->goHome();

		$model = Project::findOne($id);

		if ($model->load(Yii::$app->request->post()) && $model->validate()) {
			$model->title = Yii::$app->request->post()['Project']['title'];
			$model->desc = Yii::$app->request->post()['Project']['desc'];
			$model->save();
			return $this->redirect(['index']);
		}

		return $this->render('add-project', [
			'model' => $model,
		]);
	}

	public function actionDeleteProject($id) {
		if (Yii::$app->user->isGuest) {
			return $this->goHome();
		}

		$model = Project::findOne($id);
		$model->delete();
		return $this->redirect(['index']);
	}

	public function actionSignup() {

		$this->layout = 'login';

		$model = new SignUpForm();

		if(isset($_POST['SignUpForm'])) {
			$model->attributes = Yii::$app->request->post('SignUpForm');
			if($model->validate() && $model->signup()) {
				return $this->redirect(['login']);
			}
		}

		return $this->render('signup', [
			'model' => $model,
		]);
	}

	public function actionLogin() {
		if (!Yii::$app->user->isGuest) {
			return $this->goHome();
		}
		
		$this->layout = 'login';

		$model = new Login();

		if( Yii::$app->request->post('Login')) {
			$model->attributes = Yii::$app->request->post('Login');
			$user = $model->getUser();
			if($model->validate()) {
				Yii::$app->user->login($user);
				return $this->goHome();
			}
		}

		return $this->render('login', [
			'model' => $model,
		]);
	}

	public function actionLogout() {
		Yii::$app->user->logout();
		return $this->goHome();
	}

	public function getProjects() {
		$projects = [];
		$all_projects = Project::find()->all();

		for ($i=0; $i < count($all_projects); $i++) $projects[$all_projects[$i]->id] = $all_projects[$i]->title;

		return $projects;
	}

}

backend/views/layouts/content.php
<?php
use yii\widgets\Breadcrumbs;
use yii\widgets\AlertLte;

?>
<div class="content-wrapper">
	<section class="content-header">
		<?php if (isset($this->blocks['content-header'])) { ?>
			<h1><?= $this->blocks['content-header'] ?></h1>
		<?php } else { ?>
			<h1>
				<?php
				if ($this->title !== null) {
					echo \yii\helpers\Html::encode($this->title);
				} else {
					echo \yii\helpers\Inflector::camel2words(
						\yii\helpers\Inflector::id2camel($this->context->module->id)
					);
					echo ($this->context->module->id !== \Yii::$app->id) ? '<small>Module</small>' : '';
				} ?>
			</h1>
		<?php } ?>

		<?=
		Breadcrumbs::widget([
			'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
		]) ?>
	</section>

	<section class="content">
		<?= $content ?>
	</section>
</div>

backend/views/layouts/header.php
<?php
use yii\helpers\Html;
?>
<header class="main-header">
	<!-- Logo -->
	<a href="/" class="logo">
		<!-- mini logo for sidebar mini 50x50 pixels -->
		<span class="logo-mini"><b>EP</b></span>
		<!-- logo for regular state and mobile devices -->
		<span class="logo-lg"><b>Enterprise</b></span>
	</a>
	<!-- Header Navbar: style can be found in header.less -->
	<nav class="navbar navbar-static-top" role="navigation">
		<!-- Sidebar toggle button-->
		<a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
			<span class="sr-only">Toggle navigation</span>
		</a>
		<div class="navbar-custom-menu">
			<ul class="nav navbar-nav">
				<!-- User Account: style can be found in dropdown.less -->
				<li class="dropdown user user-menu">
					<a href="/" class="dropdown-toggle" data-toggle="dropdown">
						<span style="margin-right: 10px;margin-top: -2px;width: 25px;height: 25px;background: #ececec;display: inline-block;line-height: 25px;color: #333030;text-align: center;border-radius: 50%;font-size: 12px;">
							<?= ucfirst(\Yii::$app->user->identity->username[0]) ?>
						</span>
						<span class="hidden-xs"><?= \Yii::$app->user->identity->username ?></span>
					</a>
					<ul class="dropdown-menu">
						<li class="user-footer">
							<div class="pull-right">
								<a href="/admin/site/logout" class="btn btn-default btn-flat">Выход</a>
							</div>
						</li>
					</ul>
				</li>
			</ul>
		</div>
	</nav>
</header>

backend/views/layouts/leftside.php
<?php

use adminlte\widgets\Menu;
use yii\helpers\Html;
use yii\helpers\Url;

use common\models\{
	Project,
	User
};

$route = $this->context->route;

$project = Project::getAllNav($route);

$project[] = [ 'label' => 'Добавить задачу', 'icon' => 'fa fa-plus',  'url' => ['/site/add-project'], 'active' => $route == 'site/add-project' ];

$items = [
	['label' => 'Меню', 'options' => ['class' => 'header']],
	[ 'label' => 'Главная', 'icon' => 'fa fa-home',  'url' => ['/'], 'active' => $route == 'site/index']
];

if (User::isWorker()){
	$items[] = ['label' => 'Мои задачи', 'icon' => 'fa fa-trello', 'url' => ["/site/my"], 'active' => $route == 'site/my']; 
} else {
	$items[] = [ 'label' => 'Задачи', 'icon' => 'fa fa-trello', 'url' => '#', 'items' => $project]; 
}


?>
<aside class="main-sidebar">
	<section class="sidebar">
		<div class="user-panel">
			<div class="pull-left image">
				<span style="width: 45px;height: 45px;background: #ececec;display: block;line-height: 45px;color: #333030;text-align: center;border-radius: 50%;font-size: 22px;">
					<?= ucfirst(\Yii::$app->user->identity->username[0]) ?>
				</span>
			</div>
			<div class="pull-left info">
				<p><?= \Yii::$app->user->identity->username ?></p>
				<a href=""><i class="fa fa-circle text-success"></i> Online</a>
			</div>
		</div>
		<?=
			Menu::widget(
				[
					'options' => ['class' => 'sidebar-menu'],
					'items' => $items,
				]
			)
		?>
	</section>
</aside>

backend/views/layouts/login.php
<?php
use backend\assets\AppAsset;
use yii\helpers\Html;
use backend\assets\AdminLteAsset;

AdminLteAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
	<meta charset="<?= Yii::$app->charset ?>"/>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<?= Html::csrfMetaTags() ?>
	<title><?= Html::encode($this->title) ?></title>
	<?php $this->head() ?>
</head>
<body class="login-page" style="background: #f5f5f5;">

	<?php $this->beginBody() ?>

	<?= $content ?>

	<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

backend/views/layouts/main.php
<?php
use yii\helpers\Html;
use backend\assets\AppAsset;
use backend\assets\AdminLteAsset;

//AppAsset::register($this);
$asset      = AdminLteAsset::register($this);
$baseUrl    = $asset->baseUrl;

use backend\assets\FontAwesomeAsset;
FontAwesomeAsset::register($this);

?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body class="hold-transition skin-black-light sidebar-mini">
<?php $this->beginBody() ?>

<div class="wrapper">
    <?= $this->render('header.php', ['baserUrl' => $baseUrl, 'title'=>Yii::$app->name]) ?>
    <?= $this->render('leftside.php', ['baserUrl' => $baseUrl]) ?>

    <?= $this->render('content.php', ['content' => $content]) ?>

    <footer class="main-footer">
        Copyright &copy; <?= date('Y') ?> Все права защищены.
    </footer>
</div>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>